# Generated by Django 4.0.2 on 2022-02-17 19:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('prefix', models.CharField(blank=True, choices=[('1', 'Dr.'), ('2', 'Prof.'), ('3', 'Prof. Dr.'), ('4', 'Priv. Doz.'), ('5', 'B. A.'), ('6', 'M. A.'), ('7', 'B. Sc'), ('8', 'M. Sc')], default=None, max_length=2, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('street', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Diverse'), ('4', 'No Specification')], default='4', max_length=2, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('category', models.CharField(choices=[('1', 'Fashion and Accessoires'), ('2', 'Technology and Electronics'), ('3', 'Toys and Board Games'), ('4', 'Home and Furniture'), ('5', 'Art and Culture'), ('6', 'Movies and Films'), ('7', 'Garden and Terrace'), ('8', 'Pets'), ('9', 'Music and Instruments'), ('10', 'Computer- and Videogames'), ('11', 'Miscellaneous')], default='11', max_length=255)),
                ('start', models.DateField(default='17.02.2022')),
                ('end', models.DateField(default='03.03.2022')),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='auctions/static/resources/placeholder.png', force_format=None, keep_meta=True, null=True, quality=100, size=[1080, 1080], upload_to='auctions/static/resources/%Y/%m/%d')),
                ('shipping', models.CharField(choices=[('1', 'Shipping possible'), ('2', 'Only Pickup'), ('3', 'Express Shipping')], default='1', max_length=2)),
                ('state', models.CharField(blank=True, choices=[('1', 'Second Hand'), ('2', 'New')], default='1', max_length=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
