# Generated by Django 4.0.2 on 2022-02-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionmodel',
            name='short_description',
        ),
    ]
