# Generated by Django 4.0.2 on 2022-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end',
            field=models.DateField(default='2022-03-04'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start',
            field=models.DateField(default='2022-02-18'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Diverse'), ('4', 'No Specification')], default='1', max_length=2),
        ),
    ]
