# Generated by Django 4.0.2 on 2022-02-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='state',
            field=models.CharField(blank=True, choices=[('1', 'Second Hand'), ('2', 'New')], default='1', max_length=2, null=True),
        ),
    ]
