# Generated by Django 4.0.2 on 2022-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionmodel',
            name='img',
            field=models.BinaryField(default=None, editable=True),
        ),
    ]
