# Generated by Django 4.0.2 on 2022-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
