# Generated by Django 4.0.2 on 2022-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bidmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
